version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: "mongodb://admin:qwerty@mongo:27017/admin"
    depends_on:
      - mongo
    networks:
      - mongo-network

  nodetestapp:
    image: nodetestapp:1.0
    container_name: nodetestapp
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - mongo-express
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
